### ISSUE TITLE
does not work on VPS

### ISSUE THREAD

**Issue by Akurejs** [discordjs/opus#57]
I install the package on my windows computer and my music bot plays perfectly, I install the package on my windows VPS and the bot leaves the music channel as soon as it enters

```js
exports.run = async (bot, message, args, prefix) => {
    if (!message.member.voice.channel) return message.channel.send(`${bot.emotes.error} - Você não está em um canal de voz !`);

    if (!args[0]) return message.channel.send(`${bot.emotes.error} - Indique o título de uma música !`);

    bot.player.play(message, args.join(" "));
    message.react(`▶️`)
}
exports.help = {
    name: 'play',
    aliases: ['p'],
    category: 'music'
}
```

**Further details:**

- @discordjs/opus version: 0.3.3
- Node.js version: v14.15.3
- Operating system: Windows
- urgent

**Comment by iCrawl** [comment]
That is by far not enough information and probably not related to this module.

**Comment by tekiff** [comment]
I'm having the same problem, were you able to solve it?

**Comment by Qjuh** [comment]
I really hope you‘re not having the same issue. Because theirs is 3 years old, using very outdated versions of nodeJS, outdated version of `@discordjs/opus`, outdated version of discord.js and /voice, etc.
So if you have an issue with the current version of /opus look at current issues. But probably your issue isn’t even with /opus but discord.js and/or /voice, so join the support discord for discord.js and ask for help there instead.
